-- ============================================
-- TopSignal database schema (PostgreSQL)
-- Purpose:
--   Store trading accounts and completed trades
--   so you do not need to hit the Topstep API
--   every time you load your dashboard.
-- ============================================


-- ============================================
-- TABLE: accounts
-- One row per trading account you track.
-- Examples:
--   provider = 'topstep'
--   external_id = '123456' (the ID Topstep gives you)
-- ============================================
create table if not exists accounts (
  -- Primary key generated by Postgres (internal ID for your app)
  id bigserial primary key,

  -- Multi-tenant owner
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',

  -- Where the account came from (Topstep now, maybe others later)
  provider text not null,

  -- The account ID from the provider (Topstep account id)
  external_id text not null,

  -- Friendly name you can show in the UI (optional)
  name text,

  -- Derived TopSignal lifecycle state from ProjectX account flags.
  account_state text not null default 'ACTIVE'
    check (account_state in ('ACTIVE','LOCKED_OUT','HIDDEN','MISSING')),

  -- Last known account capability flags from ProjectX.
  can_trade boolean,
  is_visible boolean,

  -- Visibility timeline metadata for state transitions.
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  last_missing_at timestamptz,

  -- Exactly one account can be marked as user's MAIN account.
  is_main boolean not null default false,

  -- When this row was created
  created_at timestamptz not null default now(),

  -- Prevent duplicates:
  -- You cannot have two rows with the same provider + external_id
  unique (user_id, provider, external_id)
);

create index if not exists idx_accounts_is_main
  on accounts (user_id, is_main);

create index if not exists idx_accounts_account_state
  on accounts (user_id, account_state);


-- ============================================
-- TABLE: trades
-- One row per trade (your own definition of a trade).
-- This is the main table your dashboard will query.
--
-- Notes:
-- - account_id links each trade to an account in accounts.
-- - side is limited to LONG or SHORT.
-- - closed_at, exit_price, pnl can be NULL for an open trade
--   (if you ever decide to store open trades too).
-- ============================================
create table if not exists trades (
  -- Primary key generated by Postgres (internal ID for your app)
  id bigserial primary key,

  -- Multi-tenant owner
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',

  -- Which account made the trade (foreign key to accounts.id)
  account_id bigint not null references accounts(id),

  -- Instrument symbol like 'NQ', 'ES', 'AAPL'
  symbol text not null,

  -- Direction of the trade (only LONG or SHORT allowed)
  side text not null check (side in ('LONG','SHORT')),

  -- When the trade was opened (entry time)
  opened_at timestamptz not null,

  -- When the trade was closed (exit time), optional
  closed_at timestamptz,

  -- Size of the trade (contracts or shares)
  -- numeric is used so decimals are safe
  qty numeric(18,6) not null,

  -- Entry price
  entry_price numeric(18,6) not null,

  -- Exit price, optional until trade is closed
  exit_price numeric(18,6),

  -- Profit/Loss for the trade, optional
  -- (you can compute it later or store it directly)
  pnl numeric(18,2),

  -- Fees/commissions for the trade
  -- default 0 so you do not need to pass it every time
  fees numeric(18,2) default 0,

  -- Notes you type in the dashboard (optional)
  notes text,

  -- Flag for trades where you broke a rule (default false for older data)
  is_rule_break boolean not null default false,

  -- Optional free-text category for the rule break
  rule_break_type text,

  -- When this row was created in your DB
  created_at timestamptz not null default now()
);


-- ============================================
-- INDEX: idx_trades_account_opened_at
-- Speeds up queries like:
--   "Show me trades for this account, newest first"
-- Good for account-level dashboards.
-- ============================================
create index if not exists idx_trades_account_opened_at
  on trades (account_id, opened_at desc);


-- ============================================
-- INDEX: idx_trades_symbol_opened_at
-- Speeds up queries like:
--   "Show me trades for NQ last month"
-- Good for symbol filters and symbol breakdown charts.
-- ============================================
create index if not exists idx_trades_symbol_opened_at
  on trades (symbol, opened_at desc);


-- ============================================
-- INDEX: idx_trades_is_rule_break
-- Helps rule-break summaries and behavior metrics.
-- ============================================
create index if not exists idx_trades_is_rule_break
  on trades (is_rule_break);


-- ============================================
-- TABLE: instrument_metadata
-- Futures contract metadata used for point conversions.
-- pointValue = tick_value / tick_size
-- ============================================
create table if not exists instrument_metadata (
  id bigserial primary key,
  symbol text not null unique,
  tick_size numeric(18,6) not null check (tick_size > 0),
  tick_value numeric(18,6) not null check (tick_value > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


insert into instrument_metadata (symbol, tick_size, tick_value)
values
  ('MNQ', 0.25, 0.50),
  ('MES', 0.25, 1.25),
  ('MGC', 0.10, 1.00),
  ('SIL', 0.005, 5.00)
on conflict (symbol) do nothing;


-- ============================================
-- TABLE: projectx_trade_events
-- Raw/normalized trade events from ProjectX.
-- Deduplicated by account_id + order_id + trade_timestamp.
-- ============================================
create table if not exists projectx_trade_events (
  id bigserial primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',
  account_id bigint not null,
  contract_id text not null,
  symbol text,
  side text not null check (side in ('BUY','SELL','UNKNOWN')),
  size numeric(18,6) not null,
  price numeric(18,6) not null,
  trade_timestamp timestamptz not null,
  fees numeric(18,6) not null default 0,
  pnl numeric(18,6),
  order_id text not null,
  source_trade_id text,
  status text,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, account_id, source_trade_id),
  unique (user_id, account_id, order_id, trade_timestamp)
);


-- ============================================
-- INDEX: idx_projectx_trade_events_account_ts
-- Speeds account-specific recent-trades queries.
-- ============================================
create index if not exists idx_projectx_trade_events_account_ts
  on projectx_trade_events (account_id, trade_timestamp desc);


-- ============================================
-- INDEX: idx_projectx_trade_events_symbol_ts
-- Speeds symbol filtering for trade event review.
-- ============================================
create index if not exists idx_projectx_trade_events_symbol_ts
  on projectx_trade_events (symbol, trade_timestamp desc);


-- ============================================
-- TABLE: position_lifecycles
-- Closed position lifecycle snapshots with MAE/MFE.
-- ============================================
create table if not exists position_lifecycles (
  id bigserial primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',
  account_id bigint not null,
  contract_id text not null,
  symbol text not null,
  opened_at timestamptz not null,
  closed_at timestamptz not null,
  side text not null check (side in ('LONG','SHORT')),
  max_qty numeric(18,6) not null check (max_qty > 0),
  avg_entry_at_open numeric(18,6),
  realized_pnl_usd numeric(18,6),
  mae_usd numeric(18,6),
  mfe_usd numeric(18,6),
  mae_points numeric(18,6),
  mfe_points numeric(18,6),
  mae_timestamp timestamptz,
  mfe_timestamp timestamptz,
  created_at timestamptz not null default now()
);


create index if not exists idx_position_lifecycles_account_opened
  on position_lifecycles (user_id, account_id, opened_at desc);

create index if not exists idx_position_lifecycles_contract_opened
  on position_lifecycles (user_id, contract_id, opened_at desc);


-- ============================================
-- TABLE: projectx_trade_day_syncs
-- Daily sync completeness tracking for cache safety.
-- ============================================
create table if not exists projectx_trade_day_syncs (
  id bigserial primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',
  account_id bigint not null,
  trade_date date not null,
  sync_status text not null default 'partial' check (sync_status in ('partial','complete')),
  last_synced_at timestamptz not null default now(),
  row_count integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, account_id, trade_date)
);


-- ============================================
-- INDEX: idx_projectx_trade_day_syncs_account_date
-- Speeds cache checks for account/day requests.
-- ============================================
create index if not exists idx_projectx_trade_day_syncs_account_date
  on projectx_trade_day_syncs (user_id, account_id, trade_date desc);


-- ============================================
-- TABLE: journal_entries
-- Account-scoped daily journaling entries.
-- ============================================
create table if not exists journal_entries (
  id bigserial primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',
  account_id bigint not null,
  entry_date date not null,
  title text not null,
  mood text not null check (mood in ('Focused','Neutral','Frustrated','Confident')),
  tags text[] not null default '{}',
  body text not null default '',
  version integer not null default 1,
  stats_source text,
  stats_json jsonb,
  stats_pulled_at timestamptz,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, account_id, entry_date)
);


-- ============================================
-- INDEX: idx_journal_entries_account_archived_date_updated
-- Speeds account-scoped list queries with active/archive toggle.
-- ============================================
create index if not exists idx_journal_entries_account_archived_date_updated
  on journal_entries (user_id, account_id, is_archived, entry_date desc, updated_at desc);


-- ============================================
-- INDEX: idx_journal_entries_account_mood_date
-- Speeds mood-filtered journal lookups.
-- ============================================
create index if not exists idx_journal_entries_account_mood_date
  on journal_entries (user_id, account_id, mood, entry_date desc);


-- ============================================
-- TABLE: journal_entry_images
-- Image metadata for account-scoped journal entries.
-- ============================================
create table if not exists journal_entry_images (
  id bigserial primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',
  journal_entry_id bigint not null references journal_entries(id) on delete cascade,
  account_id bigint not null,
  entry_date date not null,
  filename text not null,
  mime_type text not null,
  byte_size integer not null,
  width integer,
  height integer,
  created_at timestamptz not null default now()
);


-- ============================================
-- INDEX: idx_journal_entry_images_account_date
-- Speeds account/day image lookups.
-- ============================================
create index if not exists idx_journal_entry_images_account_date
  on journal_entry_images (user_id, account_id, entry_date);


-- ============================================
-- INDEX: idx_journal_entry_images_journal_entry
-- Speeds entry-scoped image list queries.
-- ============================================
create index if not exists idx_journal_entry_images_journal_entry
  on journal_entry_images (user_id, journal_entry_id);


-- ============================================
-- TABLE: provider_credentials
-- Encrypted per-user broker credentials.
-- ============================================
create table if not exists provider_credentials (
  id bigserial primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000000',
  provider text not null,
  username_encrypted text not null,
  api_key_encrypted text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

create index if not exists idx_provider_credentials_user_provider
  on provider_credentials (user_id, provider);
