-- ============================================
-- TopSignal database schema (PostgreSQL)
-- Purpose:
--   Store trading accounts and completed trades
--   so you do not need to hit the Topstep API
--   every time you load your dashboard.
-- ============================================


-- ============================================
-- TABLE: accounts
-- One row per trading account you track.
-- Examples:
--   provider = 'topstep'
--   external_id = '123456' (the ID Topstep gives you)
-- ============================================
create table if not exists accounts (
  -- Primary key generated by Postgres (internal ID for your app)
  id bigserial primary key,

  -- Where the account came from (Topstep now, maybe others later)
  provider text not null,

  -- The account ID from the provider (Topstep account id)
  external_id text not null,

  -- Friendly name you can show in the UI (optional)
  name text,

  -- When this row was created
  created_at timestamptz not null default now(),

  -- Prevent duplicates:
  -- You cannot have two rows with the same provider + external_id
  unique (provider, external_id)
);


-- ============================================
-- TABLE: trades
-- One row per trade (your own definition of a trade).
-- This is the main table your dashboard will query.
--
-- Notes:
-- - account_id links each trade to an account in accounts.
-- - side is limited to LONG or SHORT.
-- - closed_at, exit_price, pnl can be NULL for an open trade
--   (if you ever decide to store open trades too).
-- ============================================
create table if not exists trades (
  -- Primary key generated by Postgres (internal ID for your app)
  id bigserial primary key,

  -- Which account made the trade (foreign key to accounts.id)
  account_id bigint not null references accounts(id),

  -- Instrument symbol like 'NQ', 'ES', 'AAPL'
  symbol text not null,

  -- Direction of the trade (only LONG or SHORT allowed)
  side text not null check (side in ('LONG','SHORT')),

  -- When the trade was opened (entry time)
  opened_at timestamptz not null,

  -- When the trade was closed (exit time), optional
  closed_at timestamptz,

  -- Size of the trade (contracts or shares)
  -- numeric is used so decimals are safe
  qty numeric(18,6) not null,

  -- Entry price
  entry_price numeric(18,6) not null,

  -- Exit price, optional until trade is closed
  exit_price numeric(18,6),

  -- Profit/Loss for the trade, optional
  -- (you can compute it later or store it directly)
  pnl numeric(18,2),

  -- Fees/commissions for the trade
  -- default 0 so you do not need to pass it every time
  fees numeric(18,2) default 0,

  -- Notes you type in the dashboard (optional)
  notes text,

  -- Flag for trades where you broke a rule (default false for older data)
  is_rule_break boolean not null default false,

  -- Optional free-text category for the rule break
  rule_break_type text,

  -- When this row was created in your DB
  created_at timestamptz not null default now()
);


-- ============================================
-- INDEX: idx_trades_account_opened_at
-- Speeds up queries like:
--   "Show me trades for this account, newest first"
-- Good for account-level dashboards.
-- ============================================
create index if not exists idx_trades_account_opened_at
  on trades (account_id, opened_at desc);


-- ============================================
-- INDEX: idx_trades_symbol_opened_at
-- Speeds up queries like:
--   "Show me trades for NQ last month"
-- Good for symbol filters and symbol breakdown charts.
-- ============================================
create index if not exists idx_trades_symbol_opened_at
  on trades (symbol, opened_at desc);


-- ============================================
-- INDEX: idx_trades_is_rule_break
-- Helps rule-break summaries and behavior metrics.
-- ============================================
create index if not exists idx_trades_is_rule_break
  on trades (is_rule_break);
